Integration specs
Nessrine88/Blog-App pull request #9
Opened 2023-11-23 16:23 UTC by Nessrine88

2023-11-24 00:47 UTC, FrederickMih reviewed
Hi Team
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: 

Let's kindly fix the linter issues. A project cannot be review with failing linter checks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-24 03:19 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Nessrine88 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- All tests suites passed :+1: 
- Descriptive PR title and branch name :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/users_index_spec.rb
> +  end
- [x] `user1` was created above with a profile picture. I think we are supposed to test that when the users index page is visited(users_path), the user's profile picture(user1.photo) is visible on the page content

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/users_show_spec.rb
> +    visit users_path
- [x] Let's kindly note that we are adding tests for the user show page not index page. Let's write unit test to asserts that we can see the user profile picture(`user`.photo) displayed on this page.

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/users_show_spec.rb
> +  end
- [ ]  Having unit tests help us to keep track of the building blocks. They also help you to check that the refactoring codebase in future won't introduced bugs hence we should be testing exactly how our app is working. To minimized the number of posts in this page, we got a method that retrieved only the user's 3 most recent posts. Let's kindly ensure that if a user created at least 4 posts, only the 3 most recent posts should be seen on this page :+1:

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/users_show_spec.rb
> +  end
- [x] Hi, there's a test scenario in the requirements that came before this test:
- **Tests that redirects to the post's show page when you click on a user's post.** Please let's kindly add unit test for this aspect.

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/posts_index_spec.rb
> +  end
- [ ] As mentioned above, let's kindly refactor this test to make sure that the user's profile picture is displayed on the post index page.

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/posts_index_spec.rb
> +  end
- [Optional] We are really supposed to write unit tests that covers the user's workflow and not just a test that will passed at the end :+1:

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/posts_index_spec.rb
> +describe 'posts index', type: :system do
- [ ] As stated in the requirements, let's kindly write a unit tests `that asserts you can see a section for pagination if there are more posts than fit on the view.` :+1:

2023-11-24 03:19 UTC, FrederickMih commented on spec/integrations/posts_show_spec.rb
> +describe 'posts show', type: :system do
- [ ] I think one test is left:
- `Tests that asserts you can see the username of each commentor.`

2023-11-24 15:46 UTC, TadesseDev requested changes
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 15:46 UTC, TadesseDev commented on spec/integrations/users_show_spec.rb
> +  end
- [ ] Dear team good job updating your test as suggested by the previous reviewer, but still your test does not assert the appropriate profile picture is visible. Please make sure the `user.photo` or the link for the image `https://as1.ftcdn.net/v2/jpg/00/64/30/06/1000_F_64300613_1TYCvyzq09Go7oEVXkDQypofuaJEwKTo.jpg` is present in the page. 
- [Optional] Also consider updating the description for this test. we are only testing a single user profile picture, hence kindle remove/update the `for each user` part od the `it` blcok.

2023-11-24 15:46 UTC, TadesseDev commented on spec/integrations/users_show_spec.rb
> +  end
- [ ] Dear @Nessrine88, Good job updating your test here to test only 3 posts, but we need to make use of the `recent_posts` method inside the `user_model`, This way we can test [the method itself](https://github.com/Nessrine88/Blog-App/blob/2c21138eabe2c2d8e316fe94bd522ba95b23380a/app/models/user.rb#L17C1-L21C4url) is working fine.

2023-11-25 03:08 UTC, franclobo approved these changes
Hi @Nessrine88, @kazim110 , and @alexansaa, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/Nessrine88/Blog-App/assets/58642949/4b07126d-d684-40d0-93a3-7f50cfa76e38)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✔️ 
- All tests passed ✔️ 
- Use Capybara ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-25 07:23 UTC, merged